apiVersion: v1
kind: Service
metadata:
  name: {{ include "autonomi.fullname" . }}-worker
  labels:
    {{- include "autonomi.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  clusterIP: None
  selector:
    {{- include "autonomi.worker.selectorLabels" . | nindent 4 }}
